// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBztNvLhnmubdmW0xQkWh6AhpV4fPgNihw',
    appId: '1:1090369864065:web:dfa44aa6dcaa4e4727e880',
    messagingSenderId: '1090369864065',
    projectId: 'flutterauthfirebase-8fb2c',
    authDomain: 'flutterauthfirebase-8fb2c.firebaseapp.com',
    storageBucket: 'flutterauthfirebase-8fb2c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATWy_4OWhvmbbwwk7h5TAeMVwBHOSNSY0',
    appId: '1:1090369864065:android:9947cd69b7b8668027e880',
    messagingSenderId: '1090369864065',
    projectId: 'flutterauthfirebase-8fb2c',
    storageBucket: 'flutterauthfirebase-8fb2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDibknR07wqZkuxkKod3ZTHrf3Q_sg8zZs',
    appId: '1:1090369864065:ios:f402b4980340b17927e880',
    messagingSenderId: '1090369864065',
    projectId: 'flutterauthfirebase-8fb2c',
    storageBucket: 'flutterauthfirebase-8fb2c.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDibknR07wqZkuxkKod3ZTHrf3Q_sg8zZs',
    appId: '1:1090369864065:ios:f402b4980340b17927e880',
    messagingSenderId: '1090369864065',
    projectId: 'flutterauthfirebase-8fb2c',
    storageBucket: 'flutterauthfirebase-8fb2c.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBztNvLhnmubdmW0xQkWh6AhpV4fPgNihw',
    appId: '1:1090369864065:web:51b0004751298d4627e880',
    messagingSenderId: '1090369864065',
    projectId: 'flutterauthfirebase-8fb2c',
    authDomain: 'flutterauthfirebase-8fb2c.firebaseapp.com',
    storageBucket: 'flutterauthfirebase-8fb2c.firebasestorage.app',
  );
}
